update encounters set sector=0 where sector_raw='Sector -1,-1';
update encounters set sector=1 where sector_raw='Sector -1,-2';
update encounters set sector=2 where sector_raw='Sector -1,-3';
update encounters set sector=3 where sector_raw='Sector -1,0';
update encounters set sector=4 where sector_raw='Sector -1,1';
update encounters set sector=5 where sector_raw='Sector -1,2';
update encounters set sector=6 where sector_raw='Sector -2,-1';
update encounters set sector=7 where sector_raw='Sector -2,-2';
update encounters set sector=8 where sector_raw='Sector -2,-3';
update encounters set sector=9 where sector_raw='Sector -2,0';
update encounters set sector=10 where sector_raw='Sector -2,1';
update encounters set sector=11 where sector_raw='Sector -2,2';
update encounters set sector=12 where sector_raw='Sector -3,-1';
update encounters set sector=13 where sector_raw='Sector -3,-2';
update encounters set sector=14 where sector_raw='Sector -3,-3';
update encounters set sector=15 where sector_raw='Sector -3,0';
update encounters set sector=16 where sector_raw='Sector -3,1';
update encounters set sector=17 where sector_raw='Sector -3,2';
update encounters set sector=18 where sector_raw='Sector 0,-1';
update encounters set sector=19 where sector_raw='Sector 0,-2';
update encounters set sector=20 where sector_raw='Sector 0,-3';
update encounters set sector=21 where sector_raw='Sector 0,0';
update encounters set sector=22 where sector_raw='Sector 0,1';
update encounters set sector=23 where sector_raw='Sector 0,2';
update encounters set sector=24 where sector_raw='Sector 1,-1';
update encounters set sector=25 where sector_raw='Sector 1,-2';
update encounters set sector=26 where sector_raw='Sector 1,-3';
update encounters set sector=27 where sector_raw='Sector 1,0';
update encounters set sector=28 where sector_raw='Sector 1,1';
update encounters set sector=29 where sector_raw='Sector 1,2';
update encounters set sector=30 where sector_raw='Sector 2,-1';
update encounters set sector=31 where sector_raw='Sector 2,-2';
update encounters set sector=32 where sector_raw='Sector 2,-3';
update encounters set sector=33 where sector_raw='Sector 2,0';
update encounters set sector=34 where sector_raw='Sector 2,1';
update encounters set sector=35 where sector_raw='Sector 2,2';
update encounters set event=0 where eventName='EventResponseBlackMarketFleet';
update encounters set event=1 where eventName='EventResponseCelebritySighting';
update encounters set event=2 where eventName='EventResponseIFFDisruption';
update encounters set event=3 where eventName='EventResponseWormholeAnomaly';
update encounters set event=4 where eventName='EventResponseZero-PointAnomaly';
update encounters set event=5 where eventName='Test.Travel.Explore';
update encounters set event=6 where eventName='Test.Travel.GoFightStsuff';
update encounters set event=7 where eventName='TraverseSector';
