apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacuumrs
  labels:
    app: vacuumrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vacuumrs
  template:
    metadata:
      labels:
        app: vacuumrs
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: default
      containers:
      - name: vacuumrs
        envFrom:
          - secretRef: 
              name: stk-redshift-creds
        image: 584416962002.dkr.ecr.us-west-2.amazonaws.com/rsloader:arm-0.9
        imagePullPolicy: Always
        command: ["/vacuum.sh"]
        envFrom:
          - secretRef:
              name: stk-redshift-creds
      #  env:
      #    - name: SLEEP_TIME
      #      value: "5"
      #terminationGracePeriodSeconds: 1
