apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 100k
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-arm-us-west-2
    kind: AWS
    securityGroupSelector:
      kubernetes.io/cluster/arm-us-west-2: owned
    subnetSelector:
      Name: 'eksctl-arm-us-west-2-cluster*Public*'
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: 
    - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
  - key: node.kubernetes.io/instance-type
    operator: NotIn
    values: 
    - 't4.micro'
  ttlSecondsAfterEmpty: 30
