apiVersion: apps/v1
kind: Deployment
metadata:
  name: appupdate
  labels:
    app: appupdate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appupdate
  template:
    metadata:
      labels:
        app: appupdate
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: default
        #lifecycle: Ec2Spot
      containers:
      - name: appupdate
        envFrom:
          - secretRef: 
              name: stk-redshift-creds
        image: 584416962002.dkr.ecr.us-west-2.amazonaws.com/rsloader:arm-0.9
        imagePullPolicy: Always
        command: ["/update.sh"]
        envFrom:
          - secretRef:
              name: stk-redshift-creds
      #  env:
      #    - name: SLEEP_TIME
      #      value: "5"
      #terminationGracePeriodSeconds: 1
