
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T19:30:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6dae73131c3a676d29a54ed027e917834a4e7cba",
 "version": "1.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
