---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stknolb
  name: stknolb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stknolb
  template:
    metadata:
      labels:
        app: stknolb
    spec:
      nodeSelector:
#        karpenter.sh/provisioner-name: default
        kubernetes.io/hostname: ip-192-168-82-170.us-west-2.compute.internal
      containers:
      - env:
        image: 584416962002.dkr.ecr.us-west-2.amazonaws.com/stk:arm0.10.0
        imagePullPolicy: Always
        name: stknolb
        command: ["/stk-code/start-server.sh"]
        ports:
          - name: tcp
            containerPort: 80
            protocol: TCP
          - name: udp
            containerPort: 8081
            protocol: UDP
        #readinessProbe:
        #  tcpSocket:
        #    port: 8080
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        #livenessProbe:
        #  tcpSocket:
        #    port: 8080
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
      hostNetwork: true
